### ISSUE TITLE
i18n fr_FR correction

### ISSUE THREAD

**Issue by Wilkins** [oVirt/ovirt-engine#1]
Hello,

I noticed some bad translations on french version of ovirt, and I wanted to push some corrections in the following file : 
<pre>
ovirt-engine/frontend/webadmin/modules/webadmin/src/main/resources/org/ovirt/engine/ui/webadmin/ApplicationConstants_fr_FR.properties
</pre>

But apparently, the file was auto translated, cf comment in the file 
<pre>
# auto translated by TM merge
</pre>

So my question is, can I push update on i18n or is this file auto generated and will be overwritten ?

Thanks a lot for your great software.

**Comment by eco-public** [comment]
Hi Wilkins, thank you for your comment!

For translation improvement suggestions, please file an oVirt BZ: 
https://bugzilla.redhat.com/enter_bug.cgi?product=ovirt-engine
The oVirt translators will look into it and, if make sense, update the translations accordingly via our translation management system. 

Thanks again!
