### ISSUE TITLE
ovirt-engine webadmin cann't open, error select * from  gettagsbyparent_id()

### ISSUE THREAD

**Issue by digoal** [oVirt/ovirt-engine#2]
When i enter ovirt-engine URL, the url cann't open, and see some error : 
root cause

javax.ejb.EJBException: org.springframework.jdbc.BadSqlGrammarException: PreparedStatementCallback; bad SQL grammar [select * from  gettagsbyparent_id()]; nested exception is org.postgresql.util.PSQLException: ERROR: function gettagsbyparent_id() does not exist
  Hint: No function matches the given name and argument types. You might need to add explicit type casts.
  Position: 16
	org.jboss.as.ejb3.tx.CMTTxInterceptor.handleExceptionInOurTx(CMTTxInterceptor.java:166)
	org.jboss.as.ejb3.tx.CMTTxInterceptor.invokeInOurTx(CMTTxInterceptor.java:230)
	org.jboss.as.ejb3.tx.CMTTxInterceptor.requiresNew(CMTTxInterceptor.java:333)
	org.jboss.as.ejb3.tx.SingletonLifecycleCMTTxInterceptor.processInvocation(SingletonLifecycleCMTTxInterceptor.java:56)
	org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
	org.jboss.as.ejb3.component.interceptors.CurrentInvocationContextInterceptor.processInvocation(CurrentInvocationContextInterceptor.java:41)
	org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
	org.jboss.as.ee.component.TCCLInterceptor.processInvocation(TCCLInterceptor.java:45)
	org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
	org.jboss.invocation.ChainedInterceptor.processInvocation(ChainedInterceptor.java:61)
	org.jboss.as.ee.component.BasicComponent.constructComponentInstance(BasicComponent.java:161)
	org.jboss.as.ee.component.BasicComponent.createInstance(BasicComponent.java:85)
	org.jboss.as.ejb3.component.singleton.SingletonComponent.getComponentInstance(SingletonComponent.java:116)
	org.jboss.as.ejb3.component.singleton.SingletonComponentInstanceAssociationInterceptor.processInvocation(SingletonComponentInstanceAssociationInterceptor.java:48)
	org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
	org.jboss.as.ejb3.tx.CMTTxInterceptor.invokeInNoTx(CMTTxInterceptor.java:211)
	org.jboss.as.ejb3.tx.CMTTxInterceptor.supports(CMTTxInterceptor.java:363)
	org.jboss.as.ejb3.tx.CMTTxInterceptor.processInvocation(CMTTxInterceptor.java:194)
	org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
	org.jboss.as.ejb3.component.interceptors.CurrentInvocationContextInterceptor.processInvocation(CurrentInvocationContextInterceptor.java:41)
	org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
	org.jboss.as.ejb3.component.interceptors.LoggingInterceptor.processInvocation(LoggingInterceptor.java:59)
	org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
	org.jboss.as.ee.component.NamespaceContextInterceptor.processInvocation(NamespaceContextInterceptor.java:50)
	org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
	org.jboss.as.ee.component.TCCLInterceptor.processInvocation(TCCLInterceptor.java:45)
	org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
	org.jboss.invocation.ChainedInterceptor.processInvocation(ChainedInterceptor.java:61)
	org.jboss.as.ee.component.ViewService$View.invoke(ViewService.java:165)
	org.jboss.as.ee.component.ViewDescription$1.processInvocation(ViewDescription.java:173)
	org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
	org.jboss.invocation.ChainedInterceptor.processInvocation(ChainedInterceptor.java:61)
	org.jboss.as.ee.component.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:72)
	org.ovirt.engine.core.common.interfaces.BackendLocal$$$view9.runPublicQuery(Unknown Source)
	org.ovirt.engine.core.WelcomeServlet.doGet(WelcomeServlet.java:82)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:734)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:847)
	org.ovirt.engine.core.branding.BrandingFilter.doFilter(BrandingFilter.java:72)
	org.ovirt.engine.core.utils.servlet.LocaleFilter.doFilter(LocaleFilter.java:64)
root cause

and in database no this function, it's only has an one parameter function.
ovirt=# \df gettagsbyparent_id
                               List of functions
 Schema |        Name        | Result data type | Argument data types |  Type  
--------+--------------------+------------------+---------------------+--------
 ovirt  | gettagsbyparent_id | SETOF tags       | v_parent_id uuid    | normal
(1 row)
It's a bug?

**Comment by david-caro** [comment]
If this is still an issue, please create a bug at https://bugzilla.redhat.com/enter_bug.cgi?product=ovirt-engine, as this tracker is not really active. Note that you might want to change the product if it's not correct.
