### ISSUE TITLE
REST api - Cloud init

### ISSUE THREAD

**Issue by xtrasmal** [oVirt/ovirt-engine#3]
Hello everyone,

I'm looking for some examples of how and when I would use cloud init when creating a new VM.
The manual is pretty obscure about it. Maybe anybody here that can give some pointers?

What I'd like to discover are:

- What does a full curl POST request using cloud-init look like? 
- Do I need to create a VM from template first, wait for it to be ready, and send cloudinit after?

I might have some other questions, but I can't ask them right now because of the lack of knowledge. If somebody could be my guide, I'd be very grateful. 

Thank you.

**Comment by sandrobonazzola** [comment]
Please note github is used only as a backup for the main development git repo at gerrit.ovirt.org.
I suggest to join users@ovirt.org for asking this question.

**Comment by mureinik** [comment]
The feature page gives a pretty detailed description: http://www.ovirt.org/Features/Cloud-Init_Integration

**Comment by david-caro** [comment]
You can also create a bug at https://bugzilla.redhat.com/enter_bug.cgi?product=ovirt-engine, as this tracker is not really active. Note that you might want to change the product if it's not correct.
