### ISSUE TITLE
I need change legacy to ovs switch mode on oVirt 4.4.10 node's (Problem)

### ISSUE THREAD

**Issue by luciflus** [oVirt/ovirt-engine#338]
Hello, Team! I need help.

I have cluster with 3 nodes oVirt 4.4.10 and common ISCSI storage and i have hosted engine installed on it.

I wont change legacy to ovs switch mode, using instruction below:
- Install first host and VM using "hosted-engine --deploy"
- In the Engine UI, change Cluster switch type from Legacy to OVS
- Shutdown the engine VM and stop vdsmd on the host.
- Manually change the switch type to ovs in /var/lib/vdsm/persistence/netconf/nets/ovirtmgmt
- Restart the host

After this changing, my hosted engine don't wont start, it says i have a problem with vnet interface, i don't know virtmanager or i don't know vnetuser. When i returned back settings from ovs to legacy mode, hosted engine start working without any problem 

When i had change file  /var/lib/vdsm/persistence/netconf/nets/ovirtmgmt on hosts without hosted engine, they are change network mode and start working as ovs switch mode, but they say - network out of sync. I tryed to migrate hosted engine from host with legacy switch to host with ovs switch, hosted engine don't wont migrate.

How can i migrate my infrastructure on ovs switch.

**Comment by sandrobonazzola** [comment]
oVirt 4.4 reached End Of Life, please try to reproduce with oVirt 4.5.
