### ISSUE TITLE
ovirt4.5.4 node deploy error

### ISSUE THREAD

**Issue by ringwilling** [oVirt/ovirt-engine#829]
manage control 4.5.4
node ios download from website
deploy error as blow:
2023-04-04 13:13:26 CST - TASK [ovirt-provider-ovn-driver : Install ovs] *********************************
2023-04-04 13:13:26 CST - {
  "uuid" : "778f6315-eab0-49ce-8101-37e0cce3685d",
  "counter" : 402,
  "stdout" : "fatal: [192.168.125.185]: FAILED! => {\"msg\": \"The conditional check 'cluster_switch == \\\"ovs\\\" or (ovn_central is defined and ovn_central | ipaddr)' failed. The error was: The ipaddr filter requires python's netaddr be installed on the ansible controller\\n\\nThe error appears to be in '/usr/share/ovirt-engine/ansible-runner-service-project/project/roles/ovirt-provider-ovn-driver/tasks/configure.yml': line 3, column 5, but may\\nbe elsewhere in the file depending on the exact syntax problem.\\n\\nThe offending line appears to be:\\n\\n- block:\\n  - name: Install ovs\\n    ^ here\\n\"}",
  "start_line" : 397,
  "end_line" : 398,

pls help and want an answer thanks!

**Comment by michalskrivanek** [comment]
this was addressed in #826
