### ISSUE TITLE
VmResource cannot be found

### ISSUE THREAD

**Issue by yongshengma** [oVirt/ovirt-engine#830]
Hello,
I'm not sure if it's appropriate to ask this question as an issue.  I just cannot find **`VmResource`** interface in ovirt-engine project. Here's a concrete place where it shows up in BackendVmResource.java.

```
`import org.ovirt.engine.api.resource.VmResource;

public class BackendVmResource
        extends AbstractBackendActionableResource<Vm, org.ovirt.engine.core.common.businessentities.VM>
        implements VmResource {`
```

Just cannot recognize `import org.ovirt.engine.api.resource.VmResource; `

Any idea? 

Sincerely,
Yongsheng

**Comment by bennyz** [comment]
These interfaces are generated automatically from https://github.com/oVirt/ovirt-engine-api-model by https://github.com/oVirt/ovirt-engine-api-metamodel

This would be vm resource definition:
https://github.com/oVirt/ovirt-engine-api-model/blob/master/src/main/java/services/VmService.java

**Comment by yongshengma** [comment]
Thanks for reply. I will try to follow it.
