### ISSUE TITLE
Would like to know gluster group profile used in hyperconverged deployment

### ISSUE THREAD

**Issue by kCyborg** [oVirt/ovirt-engine#834]
**Is your feature request related to a problem? Please describe.**
First of all: thanks so much for your work, awesome work!!! 
I do know this is not really an issue/enhancement, but I don't know where else ask... 
TL;DR: **I would like to know the gluster "group profile" used in hyperconverged deployment.**

Let me make myself a little bit more clear: 
i.e.: RedHat suggest a "[virt group profile](https://access.redhat.com/documentation/en-us/red_hat_gluster_storage/3.4/html/configuring_red_hat_virtualization_with_red_hat_gluster_storage/app-virt_profile)", something like the follows:

![image](https://user-images.githubusercontent.com/37458643/232930967-7390fde4-0202-4c1f-bac9-644cdf011eb7.png)

I would like to know what is the "gluster group profile" oVirt use because I can't find it in the Hyperconverged deployment.

As extra info: I will have lots of VMs running and using the SDS (glusterfs)

**Describe the solution you'd like**
Nothing, just asking and trying to squeeze all I can my hardware.

**Describe alternatives you've considered**
Nup

**Additional context**
Nup

**Comment by sandrobonazzola** [comment]
For hyperconverged gluster deployments better to ask on https://github.com/gluster/gluster-ansible
