### ISSUE TITLE
The oVirt Engine failed to add the oVirt Node host

### ISSUE THREAD

**Issue by Jack-Ywn** [oVirt/ovirt-engine#846]
**Affected version**
* oVirt Engine: (ovirt-engine-4.5.4-1.el8)
* Host OS Variant: (oVirt Node 4.5.4)

**Describe the bug**

The oVirt Engine failed to add the oVirt Node host

**Error log**
`
2023-05-14 17:19:24 CST - TASK [ovirt-provider-ovn-driver : Install ovs] *********************************
2023-05-14 17:19:24 CST - {
  "uuid" : "40f7f735-abeb-44f5-83fa-f50dd978ac1e",
  "counter" : 402,
  "stdout" : "fatal: [nd81]: FAILED! => {\"msg\": \"The conditional check 'cluster_switch == \\\"ovs\\\" or (ovn_central is defined and ovn_central | ipaddr)' failed. The error was: The ipaddr filter requires python's netaddr be installed on the ansible controller\\n\\nThe error appears to be in '/usr/share/ovirt-engine/ansible-runner-service-project/project/roles/ovirt-provider-ovn-driver/tasks/configure.yml': line 3, column 5, but may\\nbe elsewhere in the file depending on the exact syntax problem.\\n\\nThe offending line appears to be:\\n\\n- block:\\n  - name: Install ovs\\n    ^ here\\n\"}",
  "start_line" : 397,
  "end_line" : 398,
  "runner_ident" : "1f30fd4f-e63e-48e0-9de3-1e5ba9d67b25",
  "event" : "runner_on_failed",
  "pid" : 4746,
  "created" : "2023-05-14T09:19:22.697813",
  "parent_uuid" : "005056a0-771c-c938-75e8-000000000039",
  "event_data" : {
    "playbook" : "ovirt-host-deploy.yml",
    "playbook_uuid" : "0519de90-159a-44fb-9793-567651c30524",
    "play" : "all",
    "play_uuid" : "005056a0-771c-c938-75e8-000000000002",
    "play_pattern" : "all",
    "task" : "Install ovs",
    "task_uuid" : "005056a0-771c-c938-75e8-000000000039",
    "task_action" : "ansible.builtin.package",
    "task_args" : "",
    "task_path" : "/usr/share/ovirt-engine/ansible-runner-service-project/project/roles/ovirt-provider-ovn-driver/tasks/configure.yml:3",
    "role" : "ovirt-provider-ovn-driver",
    "host" : "nd81",
    "remote_addr" : "nd81",
    "res" : {
      "msg" : "The conditional check 'cluster_switch == \"ovs\" or (ovn_central is defined and ovn_central | ipaddr)' failed. The error was: The ipaddr filter requires python's netaddr be installed on the ansible controller\n\nThe error appears to be in '/usr/share/ovirt-engine/ansible-runner-service-project/project/roles/ovirt-provider-ovn-driver/tasks/configure.yml': line 3, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n- block:\n  - name: Install ovs\n    ^ here\n",
      "_ansible_no_log" : false
    },
    "start" : "2023-05-14T09:19:22.598696",
    "end" : "2023-05-14T09:19:22.697449",
    "duration" : 0.098753,
    "ignore_errors" : null,
    "event_loop" : null,
    "uuid" : "40f7f735-abeb-44f5-83fa-f50dd978ac1e"
  }
}

2023-05-14 17:19:24 CST - {
  "uuid" : "40f7f735-abeb-44f5-83fa-f50dd978ac1e",
  "counter" : 402,
  "stdout" : "fatal: [nd81]: FAILED! => {\"msg\": \"The conditional check 'cluster_switch == \\\"ovs\\\" or (ovn_central is defined and ovn_central | ipaddr)' failed. The error was: The ipaddr filter requires python's netaddr be installed on the ansible controller\\n\\nThe error appears to be in '/usr/share/ovirt-engine/ansible-runner-service-project/project/roles/ovirt-provider-ovn-driver/tasks/configure.yml': line 3, column 5, but may\\nbe elsewhere in the file depending on the exact syntax problem.\\n\\nThe offending line appears to be:\\n\\n- block:\\n  - name: Install ovs\\n    ^ here\\n\"}",
  "start_line" : 397,
  "end_line" : 398,
  "runner_ident" : "1f30fd4f-e63e-48e0-9de3-1e5ba9d67b25",
  "event" : "runner_on_failed",
  "pid" : 4746,
  "created" : "2023-05-14T09:19:22.697813",
  "parent_uuid" : "005056a0-771c-c938-75e8-000000000039",
  "event_data" : {
    "playbook" : "ovirt-host-deploy.yml",
    "playbook_uuid" : "0519de90-159a-44fb-9793-567651c30524",
    "play" : "all",
    "play_uuid" : "005056a0-771c-c938-75e8-000000000002",
    "play_pattern" : "all",
    "task" : "Install ovs",
    "task_uuid" : "005056a0-771c-c938-75e8-000000000039",
    "task_action" : "ansible.builtin.package",
    "task_args" : "",
    "task_path" : "/usr/share/ovirt-engine/ansible-runner-service-project/project/roles/ovirt-provider-ovn-driver/tasks/configure.yml:3",
    "role" : "ovirt-provider-ovn-driver",
    "host" : "nd81",
    "remote_addr" : "nd81",
    "res" : {
      "msg" : "The conditional check 'cluster_switch == \"ovs\" or (ovn_central is defined and ovn_central | ipaddr)' failed. The error was: The ipaddr filter requires python's netaddr be installed on the ansible controller\n\nThe error appears to be in '/usr/share/ovirt-engine/ansible-runner-service-project/project/roles/ovirt-provider-ovn-driver/tasks/configure.yml': line 3, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n- block:\n  - name: Install ovs\n    ^ here\n",
      "_ansible_no_log" : false
    },
    "start" : "2023-05-14T09:19:22.598696",
    "end" : "2023-05-14T09:19:22.697449",
    "duration" : 0.098753,
    "ignore_errors" : null,
    "event_loop" : null,
    "uuid" : "40f7f735-abeb-44f5-83fa-f50dd978ac1e"
  }
}
`

**Screenshots**
![image](https://github.com/oVirt/ovirt-engine/assets/72083949/57c8e41b-e126-405d-a821-fa8e51b72ed5)
![image](https://github.com/oVirt/ovirt-engine/assets/72083949/b8c9eed9-9e36-495f-868b-bb272b3dccb3)
![image](https://github.com/oVirt/ovirt-engine/assets/72083949/a52b2f54-c6e9-4f6f-8f1e-79a32f4c3f63)

**Comment by Jack-Ywn** [comment]
I would like to receive some troubleshooting steps for adding failures .Thank you very much.

**Comment by michalskrivanek** [comment]
this is resolved in nightlies since #826. See update and procedure at https://lists.ovirt.org/archives/list/users@ovirt.org/thread/DMCC5QCHL6ECXN674JOLABH36U2LVJLJ/
