### ISSUE TITLE
Cannot install ovirt engine - rockylinux 9

### ISSUE THREAD

**Issue by junnbj** [oVirt/ovirt-engine#847]
Im try to install ovirt engine in rocky linux 9, but show me this error:

 Problem: package ovirt-engine-4.5.4-1.el9.noarch requires ovirt-provider-ovn >= 1.2.1, but none of the providers can be installed
  - package ovirt-provider-ovn-1.2.36-1.el9.noarch requires ovirt-python-openvswitch >= 2.15, but none of the providers can be installed
  - cannot install the best candidate for the job
  - nothing provides python3-openvswitch2.15 needed by ovirt-python-openvswitch-2.15-3.el9.noarch
  - nothing provides python3-openvswitch2.15 needed by ovirt-python-openvswitch-2.15-4.el9.noarch
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)

Try to search this package in internet, but i not have luck. Help me?

**Comment by michalskrivanek** [comment]
there are multiple respos and includes/excludes to work around conflicts, https://github.com/oVirt/ovirt-release/blob/master/ovirt-el9-stream-x86_64-deps.repo.in should give you an idea. 
Hope this helps

(and closing the issue as it is not technically a bug, we only test CentOS Stream, not Rocky. we're open to patches though!)
