### ISSUE TITLE
How to Disable Nouveau Driver on ovirt node 4.5.4?

### ISSUE THREAD

**Issue by Jack-Ywn** [oVirt/ovirt-engine#848]
##  Description

I encountered issues with the Nouveau driver on oVirt Node 4.5.4 and wanted to disable it. I have tried several steps, but the driver is still loading. I need guidance on the correct procedure to fully disable Nouveau and ensure it doesn't conflict with other drivers.

## Steps Taken

- System Version

```
[root@localhost ~]# cat /etc/os-release 
NAME="CentOS Stream"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8.7.2206.0"
VARIANT="oVirt Node 4.5.4"
VARIANT_ID="ovirt-node"
PRETTY_NAME="oVirt Node 4.5.4"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://www.ovirt.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
PLATFORM_ID="platform:el8
```

- Modifying the system kernel from the oVirt Engine web interface

![image](https://github.com/oVirt/ovirt-engine/assets/72083949/8a2f0143-35d9-4fb3-a54b-4f82f18952d1)

- Steps I took to disable the Nouveau driver

```
[root@localhost ~]# grubby ––update-kernel=ALL ––args="rd.driver.blacklist=nouveau nouveau.modeset=0"
[root@localhost ~]# mv /boot/initramfs-$(uname -r).img /boot/initramfs-$(uname -r).img.bak
[root@localhost ~]# echo "blacklist nouveau" > /etc/modprobe.d/nouveau-blacklist.conf 
[root@localhost ~]# dracut /boot/initramfs-$(uname -r).img $(uname -r)
[root@localhost ~]# reboot
```

- After rebooting the system, I checked and found that the Nouveau driver was not successfully disabled

```
[root@localhost ~]# lsmod | grep -i nouveau
nouveau              2351104  0
mxm_wmi                16384  1 nouveau
wmi                    32768  2 mxm_wmi,nouveau
video                  49152  1 nouveau
i2c_algo_bit           16384  2 ast,nouveau
drm_ttm_helper         16384  3 drm_vram_helper,ast,nouveau
ttm                    73728  3 drm_vram_helper,drm_ttm_helper,nouveau
drm_kms_helper        266240  5 drm_vram_helper,ast,nouveau
drm                   585728  7 drm_kms_helper,drm_vram_helper,ast,drm_ttm_helper,ttm,nouveau
```

## Issue

Despite my attempts, the Nouveau driver is still loading and causing conflicts (conflict with vGPU driver). I need guidance on the correct steps to fully disable the Nouveau driver on oVirt Node 4.5.4.
Thank you for your assistance!

**Comment by Netbulae** [comment]
Nvidia has a page about this and the steps are slightly different. Maybe you can try those exact steps and see if it works?

https://docs.nvidia.com/ai-enterprise/deployment-guide-vmware/0.1.0/nouveau.html

**Comment by Jack-Ywn** [comment]
```shell
cat <<EOF > /etc/modprobe.d/blacklist.conf
blacklist nouveau
options nouveau modeset=0
EOF

cat <<EOF > /usr/lib/modprobe.d/blacklist.conf
blacklist nouveau
options nouveau modeset=0
EOF

dracut -f

reboot
```
