### ISSUE TITLE
Custom VNC Client 

### ISSUE THREAD

**Issue by bilelzr** [oVirt/ovirt-engine#872]
Hello , 
Can i use a custom Vnc Client like TigerVNC ? any guide for this ? 
thanks in advance

**Comment by michalskrivanek** [comment]
yes you can. you have to parse the information from the console.vv file manually and translate into arguments.
I think tigervnc doesn't support VeNCrypt extension for secure vnc though

**Comment by bilelzr** [comment]
> yes you can. you have to parse the information from the console.vv file manually and translate into arguments. I think tigervnc doesn't support VeNCrypt extension for secure vnc though

thank you :)
