### ISSUE TITLE
libvirt 8.9 in oVirt 4.5.4 causes log flooding w/ "Invalid value '-1' for 'cpu.max': Invalid argument"

### ISSUE THREAD

**Issue by IOMadness** [oVirt/ovirt-engine#879]
**Affected version**
oVirt 4.5.4

> **IMPORTANT!**: oVirt prior to 4.5 reached end of life.
> If you have an issue on an older version please
> upgrade to latest stable release before opening an issue.

* oVirt Engine: ovirt-engine-4.5.4-1.el8.src.rpm
* Host OS Variant: oVirt Node 4.5.4
* VDSM version: vdsm-4.50.3.4-1.el9.src.rpm
* Additional relevant package versions: none

**Describe the bug**

When running newer VMs running RHEL9 on a given host, the hosts fills the /var/log/messages file w/ the following error:
journal[2667]: Invalid value '-1' for 'cpu.max': Invalid argument

These messages come through once every minute for every VM having issues, so it takes up quite a bit of log space.

**To reproduce**

Create a VM w/ RHEL9 and run on oVirt Node 4.5.4.

**Expected behavior**

I would expect no logs to be logged regardless of what OS the VM is running.

**Screenshots**

n/a

**Additional context**

n/a

**Comment by antonios-f** [comment]
It is the libvirt issue. Fixed in https://gitlab.com/libvirt/libvirt/-/commit/e44b338ae615e03ae84584ec8998741056407ae8
