### ISSUE TITLE
upgrade  spice in ovirt

### ISSUE THREAD

**Issue by xiaonaiquan** [oVirt/ovirt-engine#888]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is

spice protocol is too old, I want to upgrade it in ovirt, what do I do?

**Describe the solution you'd like**
A clear and concise description of what you want to happen

I tried to replace libspice directly and found that it relies on a lot of libraries, such as openssl, too much to run successfully, do you have any good suggestions?

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered

**Additional context**
Add any other context or screenshots about the feature request here

**Comment by sandrobonazzola** [comment]
If you really need Spice, I would suggest to get in touch with Spice protocol community https://www.spice-space.org/ and work with them to get the newer spice protocol packaged for CentOS Virtualization SIG.
Please note Spice has been dropped in CentOS Stream 9 so the recommendation is to use a different protocol.

**Comment by xiaonaiquan** [comment]
> If you really need Spice, I would suggest to get in touch with Spice protocol community https://www.spice-space.org/ and work with them to get the newer spice protocol packaged for CentOS Virtualization SIG. Please note Spice has been dropped in CentOS Stream 9 so the recommendation is to use a different protocol.

@sandrobonazzola If the spice protocol is deleted and cannot be used, how do you remote Windows? There seems to be no open source protocol to use.

**Comment by sandrobonazzola** [comment]
I guess you can use https://www.freerdp.com/ or https://tigervnc.org/ to remote desktop Windows VMs

**Comment by xiaonaiquan** [comment]
> I guess you can use https://www.freerdp.com/ or https://tigervnc.org/ to remote desktop Windows VMs

Thank you. I'll find out
