### ISSUE TITLE
Does Ovirt support OL9VM template ?

### ISSUE THREAD

**Issue by hippoqian** [oVirt/ovirt-engine#894]
**Affected version**
4.4
> **IMPORTANT!**: oVirt prior to 4.5 reached end of life.
> If you have an issue on an older version please
> upgrade to latest stable release before opening an issue.

* oVirt Engine: 4.4.10.7-1.0.25.el8
* Host OS Variant: (example: oVirt Node 4.5.4)
* VDSM version: (example: vdsm-4.50.1.4-1.el8.x86_64)
* Additional relevant package versions: (add whatever seems related to the issue, example: glusterfs-10.2-1.el8s.x86_64)

**Describe the bug**

Trying to provision a VM with OL9 template. 
the OS type is ol_9x64, it doesn't assign IP to the VM.

Wonder if this is caused by Ovirt 4.4 doesn't support OL9.
Does Ovirt 4.5 support OL9?

**Comment by sandrobonazzola** [comment]
4.4 is EOL, please upgrade to 4.5. If this is still an in 4.5 please open a new issue.
