### ISSUE TITLE
virt-v2v is failing on importing VMware to Ovirt 4.5

### ISSUE THREAD

**Issue by Spatanaik** [oVirt/ovirt-engine#910]
**Affected version**
Ovirt-engine: 4.5
kvm host :centos 8 stream
vdsm: vdsm-4.50.5.1-1.el8.x86_64
virt-v2v: virt-v2v-1.42.0-22.module_el8+310+72016cce.x86_64
libguestfs : libguestfs-1.44.0-9.module_el8+310+72016cce.x86_64

> **IMPORTANT!**: oVirt prior to 4.5 reached end of life.

**Describe the bug**

i am trying to import a VM from vmware to ovirt4.5
I have installed virtio drivers in guest vm depoyed in vmware.
I also followed the vcenter workaround mentioned in : https://bugzilla.redhat.com/show_bug.cgi?id=1848862
Allowed maximum http sessions in vcenter conf file.

**To reproduce**

 virt-v2v -v -x -ic 'esx://root@esxihost.com?no_verify=1' -o rhev -os kvm_01:/gluster_storage --network ovirtmgt testvm
virt-v2v: virt-v2v 1.42.0rhel=8,release=22.module_el8+310+72016cce (x86_64)
libvirt version: 8.0.0
libguestfs: trace: set_verbose true
libguestfs: trace: set_verbose = 0
libguestfs: trace: get_backend
libguestfs: trace: get_backend = "libvirt"
[   0.0] Opening the source -i libvirt -ic esx://root@esxhost.com?no_verify=1 testvm
input_libvirt_vcenter_https: source: server esxhost.com
2024-01-02 20:00:22.980+0000: 33342: info : libvirt version: 8.0.0, package: 22.module_el8+596+27e96798 (builder@centos.org, 2023-07-31-14:36:36, )
2024-01-02 20:00:22.980+0000: 33342: info : hostname: kvm_01.domain.com
2024-01-02 20:00:22.980+0000: 33342: warning : esxConnectOpen:806 : Ignoring unexpected path '' for non-vpx scheme 'esx'
Enter root's password for esxhost.com:
libvirt xml is:
<domain type='vmware' xmlns:vmware='http://libvirt.org/schemas/domain/vmware/1.0'>
  <name>testvm</name>
  <uuid>4206c6b5-e243-766f-8bb8-fe9bc90311c1</uuid>
  <genid>8307dde5-6f1c-42a2-bd3a-75351570ad6e</genid>
  <description>Test VM for LAB</description>
  <memory unit='KiB'>4194304</memory>
  <currentMemory unit='KiB'>4194304</currentMemory>
  <vcpu placement='static'>2</vcpu>
  <cputune>
    <shares>2000</shares>
  </cputune>
  <os firmware='efi'>
    <type arch='x86_64'>hvm</type>
  </os>
  <clock offset='utc'/>
  <on_poweroff>destroy</on_poweroff>
  <on_reboot>restart</on_reboot>
  <on_crash>destroy</on_crash>
  <devices>
    <disk type='file' device='disk'>
      <source file='[vsandatastore] c9455064-3c35-9b1f-8dcd-3cfdfe874fa8/testvm.vmdk'/>
      <target dev='sda' bus='scsi'/>
      <address type='drive' controller='0' bus='0' target='0' unit='0'/>
    </disk>
    <disk type='file' device='cdrom'>
      <source file='[vsanDatastore] 443d7a35-325f-cf2b-8bfb-3cfdfe874fa8/virtio-win-0.1.240.iso'/>
      <target dev='sda' bus='sata'/>
      <readonly/>
      <address type='drive' controller='0' bus='0' target='0' unit='0'/>
    </disk>
    <controller type='scsi' index='0' model='lsisas1068'/>
    <controller type='sata' index='0'/>
    <interface type='bridge'>
      <mac address='00:50:56:8378:a0' type='generated'/>
      <source bridge='vlanNetwork-119'/>
      <model type='vmxnet3'/>
    </interface>
    <video>
      <model type='vmvga' vram='8192' primary='yes'/>
    </video>
  </devices>
  <vmware:datacenterpath>ha-datacenter</vmware:datacenterpath>
  <vmware:moref>114</vmware:moref>
</domain>

Enter host password for user 'root':
'curl' -q --max-redirs '5' --globoff --head --silent --url 'https://esxhost.com/folder/c9455063-3c35-9b1f-8dcd-3cfdfe874fa8/testvm-flat.vmdk?dcPath=ha-datacenter&dsName=vsanDatastore' --user <hidden> --insecure
HTTP/1.1 404 Not Found
Date: Tue, 2 Jan 2024 20:00:37 GMT
Set-Cookie: vmware_soap_session="d2ddcb88e7562c6bfbe1a7235f863a9cf1dc7fbc"; Path=/; HttpOnly; Secure;
Connection: close
Content-Security-Policy: upgrade-insecure-requests
Content-Type: text/plain; charset=utf-8
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-XSS-Protection: 1
Content-Length: 0

'curl' -q --max-redirs '5' --globoff --head --silent --url 'https://esxhost.com/folder/c9455063-3c35-9b1f-8dcd-3cfdfe874fa8/testvm-flat.vmdk?dcPath=ha-datacenter&dsName=vsanDatastore' --user <hidden> --insecure
HTTP/1.1 404 Not Found
Date: Tue, 2 Jan 2024 20:00:37 GMT
Set-Cookie: vmware_soap_session="d2ddcb88e7562c6bfbe1a7235f863a9cf1dc7fbc"; Path=/; HttpOnly; Secure;
Connection: close
Content-Security-Policy: upgrade-insecure-requests
Content-Type: text/plain; charset=utf-8
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-XSS-Protection: 1
Content-Length: 0

virt-v2v: error: vcenter: URL not found:
https://esxhost.com/folder/c9455063-3c35-9b1f-8dcd-3cfdfe874fa8/testvm-flat.vmdk?dcPath=ha-datacenter&dsName=vsanDatastore
rm -rf '/var/tmp/null.tlXLZT'
libguestfs: trace: close
libguestfs: closing guestfs handle 0x558c8d743c00 (state 0)
[root@kvm_01 ~]#

Steps to reproduce the behavior

**Expected behavior**

the VM guest from VMware should get imported to ovirt 4.5 

**Screenshots**

NA

**Additional context**

**Comment by dupondje** [comment]
```virt-v2v: error: vcenter: URL not found:```

Don't see what it has to do with oVirt really :)

**Comment by Spatanaik** [comment]
I am managing KVM (centos8-stream flavour) in Ovirt ( management platform- equivalent to vCenter in VMware world)
I ran virt-v2v on KVM hypervisor to import a VM from Vmware vCenter to KVM. I encountered this error.

**Comment by dupondje** [comment]
It fals in virt-v2v, please report there.
This is unrelated to oVirt
