### ISSUE TITLE
host reinstall error on 4.5.6 - runs ovn when should not (ovn_central is defined)

### ISSUE THREAD

**Issue by oernii** [oVirt/ovirt-engine#949]
**Affected version**
4.5.6

* oVirt Engine: ovirt-engine-4.5.6-1.el8.noarch
* Host OS Variant: Rocky Linux 8.10
* VDSM version: vdsm-4.50.5.1-1.el8.x86_64
* Additional relevant package versions: 

**Describe the bug**
After upgrading to ovirt 4.5 engine+host I tried to reinstall the host via the menu and it always fails on the ansible task "Task Configure OVN for oVirt failed to execute." My hosts use classic bridges and OVN is not enabled on the cluster. The reinstall task however tries to run it.

**To reproduce**
reinstall a host with bridge net via engine gui

**Expected behavior**
reinstall succeeds

**Screenshots**
the ansible task tries to run "/bin/vdsm-tool ovn-config 1.2.3.4 host.domain.com" which fails

**Additional context**
I was able to make the re-install work by adding :
```
***************
*** 46,49 ****
            vdsm-tool ovn-config {{ ovn_central }} {{ ovn_tunneling_interface }} {{ ovn_host_fqdn }}
  
    when:
!     - ovn_central is defined and 1 == 2
--- 46,49 ----
            vdsm-tool ovn-config {{ ovn_central }} {{ ovn_tunneling_interface }} {{ ovn_host_fqdn }}
  
    when:
!     - ovn_central is defined
```

Also this issue has beed discussed on the mail list: https://www.mail-archive.com/users@ovirt.org/msg73341.html

**Comment by mat1010** [comment]
Can confirm. We had the exact same issue. Seems that this issue exists since this fix https://github.com/oVirt/ovirt-engine/pull/826

**Comment by dupondje** [comment]
https://github.com/oVirt/ovirt-engine/commit/f039053bf4903bc6f42babc7514c682408260bf7

Guess this will fix it?
